Repository avikantz/ikea-word-games, pull requests merged in 2023-10, with the labels that each got.

#23 Fix #21: Confetti Overlay over Successful Product Name
  src/components/bildval/guessOption.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#31 Reviewed language support for german
  src/app/i18n/locales/de/default.json
Labels: good first issue, localization, hacktoberfest, hacktoberfest-accepted

#32 Fixed typo
  src/app/i18n/locales/de/default.json
Labels: localization, hacktoberfest, hacktoberfest-accepted

#34 Fix #28: Adds product image on Ordval
  src/app/[lang]/ordval/[mode]/loading.tsx
  src/app/[lang]/ordval/[mode]/page.tsx
  src/app/[lang]/ordval/unlimited/loading.tsx
  src/app/[lang]/ordval/unlimited/page.tsx
  src/components/ordval/guessOption.tsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#35 Adds contributors list to /about
  .github/pull_request_template.md
  src/app/[lang]/about/contributors.ts
  src/app/[lang]/about/credits.ts
  src/app/[lang]/about/page.tsx
  src/app/i18n/locales/de/default.json
  src/app/i18n/locales/en/default.json
  src/app/i18n/locales/es/default.json
  src/app/i18n/locales/fr/default.json
  src/app/i18n/locales/it/default.json
  src/app/i18n/locales/pt/default.json
Labels: enhancement

#39 Add Finnish
  public/data/fi/items/list.json
  public/data/fi/items/map.json
  public/data/fi/names/10.json
  public/data/fi/names/4.json
  public/data/fi/names/5.json
  public/data/fi/names/6.json
  public/data/fi/names/7.json
  public/data/fi/names/8.json
  public/data/fi/names/9.json
  public/data/fi/names/all.json
  public/data/fi/unique/10.json
  public/data/fi/unique/4.json
  public/data/fi/unique/5.json
  public/data/fi/unique/6.json
  public/data/fi/unique/7.json
  public/data/fi/unique/8.json
  public/data/fi/unique/9.json
  public/data/fi/unique/all.json
  public/data/fi/unique/easy.json
  public/data/fi/unique/hard.json
  public/data/fi/unique/medium.json
  scripts/generate.js
  src/app/[lang]/about/contributors.ts
  src/app/i18n/locales/fi/default.json
  src/app/i18n/settings.js
Labels: localization, hacktoberfest, hacktoberfest-accepted

#40 Fix #37: Disable non-solution keyboard characters in Jumble
  src/app/[lang]/about/contributors.ts
  src/app/global.css
  src/components/wordInput.tsx
  src/utils/words.ts
Labels: bug, hacktoberfest, hacktoberfest-accepted

#43 Fix wording in English and spacing in Spanish
  src/app/i18n/locales/en/default.json
  src/app/i18n/locales/es/default.json
Labels: localization, hacktoberfest, hacktoberfest-accepted

#44 Add icon for backspace, enter, submit, physical input
  .vscode/settings.json
  public/assets/backspace-hover.svg
  public/assets/backspace.svg
  public/assets/tick-hover.svg
  public/assets/tick.svg
  src/app/[lang]/about/contributors.ts
  src/app/global.css
  src/components/Icon/Keyboard.tsx
  src/components/Icon/PhysicalKeyboard.tsx
  src/components/Icon/Return.tsx
  src/components/Icon/index.tsx
  src/components/wordInput.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#46 Add Korean
  src/app/[lang]/about/contributors.ts
  src/app/i18n/locales/en-KR/default.json
  src/app/i18n/settings.js
Labels: hacktoberfest, hacktoberfest-accepted
